-- 회원정보 입력

INSERT INTO MJOIN ( EMAIL, NICKNAME, PASSWORD, NAME, TEL)
 VALUES ( 'tree@naver.com', 'tree', '1234', '케빈', '010-9925-6798');

INSERT INTO MJOIN ( EMAIL, NICKNAME, PASSWORD, NAME, TEL)
 VALUES ( 'sexyguy@naver.com', 'sexyguy', '1234', '류우곤', '010-1234-5678');
 
INSERT INTO MJOIN ( EMAIL, NICKNAME, PASSWORD, NAME, TEL)
 VALUES ( 'coolguy@naver.com', 'coolguy', '1234', '최동호', '010-5678-1234');
 
 INSERT INTO MJOIN ( EMAIL, NICKNAME, PASSWORD, NAME, TEL)
 VALUES ( 'goodguy@naver.com', 'goodguy', '1234', '김남욱', '010-7894-1564');
 
 INSERT INTO MJOIN ( EMAIL, NICKNAME, PASSWORD, NAME, TEL)
 VALUES ( 'badguy@naver.com', 'badguy', '1234', '이삼주', '010-8989-6767');
 
  INSERT INTO MJOIN ( EMAIL, NICKNAME, PASSWORD, NAME, TEL)
 VALUES ( 'busanguy@naver.com', 'busanguy', '1234', '박세진', '010-3214-6547');

commit;


--게시글 정보 입력
INSERT INTO MPOST(POST_NUM, NICKNAME, POST_CONT ,POST_IMG, PLACE)
VALUES(SEQ_POST_NUM.NEXTVAL,'tree','나는 섹시가이','knu.jpg','경성대');

INSERT INTO MPOST(POST_NUM, NICKNAME, POST_CONT ,POST_IMG, PLACE)
VALUES(SEQ_POST_NUM.NEXTVAL,'coolguy','강호나시','no.jpg','신서유기');

INSERT INTO MPOST(POST_NUM, NICKNAME, POST_CONT ,POST_IMG, PLACE)
VALUES(SEQ_POST_NUM.NEXTVAL,'sexyguy','강호나시2','yeah.jpg','신서유기');

commit;

--좋아요 정보 입력
INSERT INTO MLIKE(LIKENUM, LIKE_POST_NUM ,LIKE_POST_USER)
VALUES(SEQ_LIKE_NUM.NEXTVAL,1,'coolguy');

INSERT INTO MLIKE(LIKENUM, LIKE_POST_NUM ,LIKE_POST_USER)
VALUES(SEQ_LIKE_NUM.NEXTVAL,2,'busanguy');

INSERT INTO MLIKE(LIKENUM, LIKE_POST_NUM ,LIKE_POST_USER)
VALUES(SEQ_LIKE_NUM.NEXTVAL,3,'busanguy');

commit;

-- 게시글 좋아요 숫자 업데이트
UPDATE MPOST 
SET LIKECOUNT = 1
WHERE POST_NUM = 1;

UPDATE MPOST 
SET LIKECOUNT = 1
WHERE POST_NUM = 2;

UPDATE MPOST 
SET LIKECOUNT = 1
WHERE POST_NUM = 3;
COMMIT;

--댓글 정보 입력
INSERT INTO MREPLY(REPLY_IDX,REPLY_WRITER,POST_NUM,REPLY_CONT,REPLY_CLASS,REPLY_ORDER,GRP_NUM)
VALUES (SEQ_REPLY_NUM.NEXTVAL,'sexyguy',1,'넌 섹시하지 않아',0,0,2);

INSERT INTO MREPLY(REPLY_IDX,REPLY_WRITER,POST_NUM,REPLY_CONT,REPLY_CLASS,REPLY_ORDER,GRP_NUM)
VALUES (SEQ_REPLY_NUM.NEXTVAL,'coolguy',1,'넌 멋지지 않아',0,1,2);

INSERT INTO MREPLY(REPLY_IDX,REPLY_WRITER,POST_NUM,REPLY_CONT,REPLY_CLASS,REPLY_ORDER,GRP_NUM)
VALUES (SEQ_REPLY_NUM.NEXTVAL,'goodguy',2,'이수근 이수근',0,0,3);

INSERT INTO MREPLY(REPLY_IDX,REPLY_WRITER,POST_NUM,REPLY_CONT,REPLY_CLASS,REPLY_ORDER,GRP_NUM)
VALUES (SEQ_REPLY_NUM.NEXTVAL,'coolguy',2,'강호동 강호동',0,1,3);

INSERT INTO MREPLY(REPLY_IDX,REPLY_WRITER,POST_NUM,REPLY_CONT,REPLY_CLASS,REPLY_ORDER,GRP_NUM)
VALUES (SEQ_REPLY_NUM.NEXTVAL,'goodguy',3,'은지원 은지원',0,0,4);

INSERT INTO MREPLY(REPLY_IDX,REPLY_WRITER,POST_NUM,REPLY_CONT,REPLY_CLASS,REPLY_ORDER,GRP_NUM)
VALUES (SEQ_REPLY_NUM.NEXTVAL,'coolguy',3,'최규현 최규현',0,1,4);
COMMIT;

--커서 작동 여부
var o_cur refcursor;
exec PKG_POST.PROC_POST_LIST(:O_CUR);
PRINT :O_CUR;

--POST 정보 출력 프로시저 작동 여부
 SELECT POST_NUM, NICKNAME ,POST_CONT ,POST_IMG, REGDATE ,PLACE
    FROM MPOST
    ORDER BY POST_NUM ASC;
    







SELECT P.POST_NUM, P.NICKNAME ,P.POST_CONT ,P.POST_IMG, P.REGDATE ,P.PLACE,
           P.LIKECOUNT, L.LIKE_POST_USER, R.REPLY_WRITER, R.REPLY_CONT, R.REGDATE ,R.GRP_NUM ,R.REPLY_ORDER
    FROM   MPOST P, MLIKE L, MREPLY R
    WHERE  P.POST_NUM = L.LIKE_POST_NUM
    AND    P.POST_NUM = R.POST_NUM
    ORDER BY POST_NUM ASC,REPLY_ORDER ASC;

  SELECT R.REPLY_IDX, R.REPLY_WRITER, R.POST_NUM, R.REPLY_CONT, R.TARGET_ID, R.REPLY_CLASS, R.REPLY_ORDER, R.GRP_NUM, R.REGDATE
    FROM MREPLY R, MPOST P
    WHERE R.POST_NUM = P.POST_NUM;
    
    select *
    from  (
    select * from MJOIN order by dbms_random.value)
    where rownum <= 5;

 SELECT EMAIL,
        NICKNAME,
        PASSWORD,
        NAME,
        TEL,
        JOINDATE,
        P_THUMBNAIL,
        P_INTRODUCE
    FROM  (
    SELECT EMAIL,
        NICKNAME,
        PASSWORD,
        NAME,
        TEL,
        JOINDATE,
        P_THUMBNAIL,
        P_INTRODUCE 
    FROM MJOIN ORDER BY dbms_random.value)
    WHERE ROWNUM <= 5;
    
    
    SELECT P.POST_NUM, P.NICKNAME ,P.POST_CONT ,P.POST_IMG, P.REGDATE ,P.PLACE,
           P.LIKECOUNT, L.LIKE_POST_USER, R.REPLY_WRITER, R.REPLY_CONT, R.REGDATE ,R.GRP_NUM ,R.REPLY_ORDER
    FROM   MPOST P, MLIKE L, MREPLY R
    WHERE  P.POST_NUM = L.LIKE_POST_NUM
    AND    P.POST_NUM = R.POST_NUM
    ORDER BY POST_NUM ASC;
    
    SELECT *
    FROM MREPLY R, MPOST P
    WHERE P.POST_NUM = R.POST_NUM;


  SELECT P.POST_NUM, P.NICKNAME ,P.POST_CONT ,P.POST_IMG, P.REGDATE ,P.PLACE,
           P.LIKECOUNT, L.LIKE_POST_USER, R.REPLY_IDX, R.REPLY_WRITER, R.POST_NUM, R.REPLY_CONT, R.TARGET_ID, R.REPLY_CLASS,
           R.REPLY_ORDER, R.GRP_NUM, R.REGDATE
    FROM   MPOST P, MLIKE L, MREPLY R
    WHERE  P.POST_NUM = L.LIKE_POST_NUM
    AND    R.POST_NUM = P.POST_NUM
    ORDER BY P.POST_NUM ASC;
    
    
      SELECT *
        FROM MREPLY R, MPOST P
        WHERE P.POST_NUM = 3
        AND   P.POST_NUM = R.POST_NUM;
        
 SELECT P.POST_NUM, P.NICKNAME, P.POST_CONT, P.POST_IMG, P.REGDATE, P.PLACE, P.LIKECOUNT,
       L.LIKENUM, L.LIKE_POST_NUM, L.LIKE_POST_USER
FROM MPOST P, MLIKE L
WHERE POST_NUM = 1
AND P.POST_NUM = L.LIKE_POST_NUM;

SELECT * 
FROM MREPLY
WHERE POST_NUM = 1;       
    