CREATE OR REPLACE
PACKAGE BODY PKG_USER AS

  PROCEDURE PROC_USER_RECOMMEND(
  O_CUR     OUT SYS_REFCURSOR
 ) AS
  BEGIN
    OPEN O_CUR FOR
    SELECT EMAIL,
        NICKNAME,
        PASSWORD,
        NAME,
        TEL,
        JOINDATE,
        P_THUMBNAIL,
        P_INTRODUCE
    FROM  (
    SELECT EMAIL,
        NICKNAME,
        PASSWORD,
        NAME,
        TEL,
        JOINDATE,
        P_THUMBNAIL,
        P_INTRODUCE 
    FROM MJOIN ORDER BY dbms_random.value)
    WHERE ROWNUM <= 5;
  END PROC_USER_RECOMMEND;
  
  PROCEDURE PROC_USER_LIST(
 O_CUR     OUT SYS_REFCURSOR
 ) AS
  BEGIN
    OPEN O_CUR FOR
    SELECT *
    FROM MJOIN;
  END PROC_USER_LIST;

END PKG_USER;