create or replace PACKAGE BODY PKG_POST AS

  PROCEDURE PROC_POST_LIST(
  O_CUR     OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN O_CUR FOR
    SELECT P.POST_NUM, P.NICKNAME ,P.POST_CONT ,P.POST_IMG, P.REGDATE ,P.PLACE,
           P.LIKECOUNT, L.LIKE_POST_USER
    FROM   MPOST P, MLIKE L
    WHERE  P.POST_NUM = L.LIKE_POST_NUM
    ORDER BY POST_NUM ASC;
  END PROC_POST_LIST;

END PKG_POST;